### ISSUE TITLE
items is data schema or JSON Object or array of data schema?

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-thing-description#364] opened 2019-01-23 17:37 UTC
in 5.3.2 ArraySchema items are noted as DataSchema, however, assertion td-data-schema-objecs ( The type of the members properties and items MUST be serialized as a JSON object. ) says that it is an object. In JSON Schema, items are allowed to be arrays for example

**Comment by egekorkan** [comment] 2019-01-31 04:51
In Princeton testfest, we have seen two use cases that used items as an array. One was from @mmccool

**Comment by egekorkan** [comment] 2019-01-31 17:50
Following the discussion on 31.01 at Princeton Testfest:

This has been discussed and we confirm that not allowing items to be array breaks JSON Schema compatibility.

**Comment by takuki** [comment] 2019-02-11 04:12
In Section [5.3.2 ArraySchema](https://cdn.staticaly.com/gh/w3c/wot-thing-description/7e22bc99c0b89f8569535d457a09928ba9dd5e86/index.html#arrayschema), "items" is about each item in the array, therefore, the type here is a generic DataSchema. On the other hand, in Section [6.1.9 Data Schema Representation](https://cdn.staticaly.com/gh/w3c/wot-thing-description/7e22bc99c0b89f8569535d457a09928ba9dd5e86/index.html#data-schema-serialization-json), "items" is about how it is written in TD. In other words, the former is about each item in the array, and the latter is about how such definition is written in TD. I think that is why the latter is an Object.

**Comment by sebastiankb** [comment] 2019-02-15 09:17
the issue is that 'items' can be DataSchema or a array of DataSchema

@vcharpenay will have a look on that.

**Comment by vcharpenay** [comment] 2019-03-15 11:58
PR #492 fixes this (sorry for mixing it with an existing PR, which I thought was merged...)

**Comment by egekorkan** [comment] 2019-03-20 12:31
This PR does fix the problem but it breaks the td-data-schema-objects assertion which says ` The type of the members properties and items MUST be serialized as a JSON object. `

I think the word items should be removed from this assertion and a new one specifically for items should be created.

**Comment by egekorkan** [comment] 2019-04-10 15:20
This is fixed with #565

**Closed** 2019-04-10 15:20 UTC
Labels: Needs review
