### ISSUE TITLE
Mandatory terms in specifications of Interaction Patterns

### ISSUE THREAD

**Issue by danicic** [w3c/wot-thing-description#117] opened 2018-03-21 14:03 UTC
According to [Section 6.2.3 Event](https://w3c.github.io/wot-thing-description/#event-serialization) there are are four mandatory terms for the Event pattern, and later in the table only three appear to be mandatory. `form` is not mandatory (the forth one). Moreover `form` is not mandatory in specifications for `Property `and `Action` too.

**Comment by mkovatsc** [comment] 2018-03-23 16:01
@sebastiankb @vcharpenay : was there a deeper plan such as Events being able to emit unsolicited push data, where no form is or can be submitted to subscribe?

I can imagine the above, but overall I think it is caused by the lack of running code and experiences from the PlugFests. We do have more implementations for Prague 2018, which starts tomorrow.

**Comment by sebastiankb** [comment] 2018-03-26 09:48
The idea of making form optional is to allow TD template definitions where communication metadata may be not needed.

**Comment by danicic** [comment] 2018-03-26 09:54
OK, but then please rephrase the sentence in the Deliverable: "There are are four mandatory terms defined within the Event pattern" ->: There are three mandatory terms defined within the Event pattern.

**Comment by sebastiankb** [comment] 2018-03-26 10:03
ahh, now I understand your issue ;-) Please use in future quotes to point this out. 

@ashimura Is it still possible to make changes in the deliverable document?

**Comment by sebastiankb** [comment] 2018-04-09 06:46
Sentence is fixed in the latest working draft 
https://www.w3.org/TR/wot-thing-description/#event-serialization

**Closed by sebastiankb** 2018-04-09 06:46 UTC
