### ISSUE TITLE
Enabling Interaction History (making Actions the only way to modify state)

### ISSUE THREAD

**Issue by lgleim** [w3c/wot-thing-description#155] opened 2018-06-19 14:45 UTC
For many applications it is important to be able to 'track changes', i.e. to  maintain a ledger of modifications and who affected them (also an important part of tracking provenance).
Inspired by the principles of Operational Transformation, a log of invoked actions additionally allows for many advantages (among others) in (real-time) state synchronization, (time-travelling) debugging, testability and accountability. Similiar concepts are immensely popular for state management in web applications and realtime collaboration frameworks. (e.g Redux, ngrx) 

Schema.org defines Actions with three kinds of "actionStatus" (Documentation http://schema.org/docs/actions.html):
- PotentialActionStatus - A description of an action that is supported
- ActiveActionStatus - An in-progress action (e..g, while watching the movie, or driving to a location)
- CompletedActionStatus - An action that has already taken place.

Completed actions can also be used to publish activity streams similar to what ActivityStreams https://www.w3.org/TR/activitystreams-core/ do.

As such I would like to start a discussion on either
   1. making Action invocations the only allowed way to modify state or 
   2. making any "write"/state change semantically interpretable as an invoked action.
 
#### RE 1
This implies that Properties must not be writable and that Event subscription requests must never change the Thing's state. Especially the latter appears to imply a limitation of expressiveness (functions that return more than one result can no longer modify state), unless the semantics of Action is changed to allow zero, one or multiple return values (or functions that return observables). Thoughts?

#### RE 2
This is basically a hack that defines writable properties and event subscriptions (at least those that do modify state) to be considerable Invocable Actions (in the sense of e.g. schema.org actions). This might well be a feasible option but increases the complexity of the WOT model, i.e. makes it harder to understand for anyone new to the field. Since there will without doubt be many proposed extensions that complicate the model, this may also be suboptimal.

Looking forward to your thoughts.

**Comment by sebastiankb** [comment] 2018-10-19 14:01
Sorry for the late response:
about 1)
The TD is defined in that way that you are open how you want to manipulate your state. So, you can make properties readOnly (writable=false) and define (write) Actions to manipulate the states of the Properties. This a valid way. However, others prefer in their implementations the direct way and offers the properties in writable manner. This way you will typical find in REST-based implementations with GET/PUT operation on a resource. 
 
about  2) This is a quite old topic in our TD group. The problem is that there is no really standard yet and it is unclear what the TD should cover about this. Currently, the IETF address this issue with CoRAL (https://tools.ietf.org/html/draft-hartke-t2trg-coral-05).

**Comment by sebastiankb** [comment] 2019-01-09 08:10
@lgleim Since there is no more responses, I will close this issue. Feel free to reopen it if the answers are not enough.

**Closed by sebastiankb** 2019-01-09 08:10 UTC
