### ISSUE TITLE
clarify permitted language tags for titles/descriptions [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#642] opened 2019-05-07 16:32 UTC
6.2.10 titles and descriptions
https://cdn.staticaly.com/gh/w3c/wot-thing-description/TD-TAG-review/index.html?env=dev#titles-descriptions-serialization-json

> Whenever the vocabulary terms titles and descriptions can be used, both MUST be serialized as JSON Object. The member names of the JSON Object MUST be the language tags as defined in [BCP47] (e.g., "en", "de", "ja", "zh-Hans", "zh-Hant"). 

The above text would be clearer with some adjustments:

* I would change "...can be used, both MUST..." to "...are used, each MUST...", on the assumption that these can appear independently from one another.

* The sentence attempting to require BCP47 language tags might be better and more clear about what is expected if written more like:

> The member names of the JSON Object MUST be valid [BCP47] language tags.

... I would note that BCP47 defines how language tags are formed and how the subtag registry is operated, but doesn't (strictly speaking) define each language tag directly. The other thing is that I dragged in the term "valid", although you might only wish to impose a normative requirement of "well-formed" (see BCP47 for details on the difference).

**Comment by mkovatsc** [comment] 2019-05-07 17:25
Thank you! We have improved the normative language already a bit and actually improved the split between model (Section 5) and serialization (Section 6). 

In Section 5, we already say "well-formed", but still need to make the assertion easier to understand. Your formulations help here.

In Section 6, we need to:
* Make two subsections, one for the default language members, one for the MultiLanguage objects.
* align the wording with the serialization of other Maps.
* Reformulate "language tags defined in [BCP47]".

@aphillips Can you recommend a good reference for the currently defined language tags? I guess it is hard, because it is a whole system of tags.

**Comment by aphillips** [comment] 2019-05-07 18:32
@mkovatsc BCP47 is a language tagging system built of valid subtags. Of course, many tags are well-formed, valid, and useless (`tlh-Cyrl-AQ-alalc97` aka "Klingon written in Cyrllic as used in Antarctica and transcribed using the Library of Congress 1997 transliteration" :-P). For guidance on which language tags are supported by modern implementations, I would use [CLDR](https://cldr.unicode.org) as the reference. There is a good article about [choosing language tags](https://www.w3.org/International/questions/qa-choosing-language-tags) in the W3C I18N site.

**Comment by aphillips** [comment] 2019-05-07 18:33
I should add... your spec isn't really about language tagging or locale choice or language negotiation. You might want to avoid incorporating a lot of recommendations and such into your spec.

**Comment by mkovatsc** [comment] 2019-05-07 18:37
My thinking was that "machine-to-machine people" implementing this might need some more information on the subject :)
Thus, this guidance on which language tags are usually supported by modern implementations might be a good informative reference.

**Comment by mmccool** [comment] 2019-05-08 05:40
Yes, a short list of valid language tags for use in IoT and Web systems would be useful.   It would be especially useful to flag cases where a script subtag is necessary to disambiguate text direction (eg. az-Latn vs. az-Arab, which is one example of I know of).   Not something that can be solved today... but maybe something the i18n group could publish as a Note.

**Comment by sebastiankb** [comment] 2019-07-04 14:41
@aphillips Please comment if the issue is now addressed. Please see last comment from Matthias.

Propose to close this issue.

**Comment by aphillips** [comment] 2019-09-26 15:49
LGTM. I18N is satisfied with this resolution. Thank you!

**Comment by sebastiankb** [comment] 2019-09-27 15:17
thank you for your feedback. I will close this issue.

**Closed by sebastiankb** 2019-09-27 15:17 UTC
Labels: Needs review, Propose closing, i18n-comment
