### ISSUE TITLE
rules and test suite for conversion between JSON schema and RDF

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/wot-thing-description#804] opened 2019-08-21 04:41 UTC
The ontology at
https://w3c.github.io/wot-thing-description/ontology/jsonschema.html
looks promising - but it is light on implementation details. 

It explicitly states "defined against schema.org's meta-model" and later provides a mapping from json terms to the RDF.  The latter seems to be a mapping from a concrete implementation of the meta model in JSON, but its not really called out explicitly.

if one wishes to use this and test it further is there any support for implementation of these rules in machine-executable form - for example a json-ld context document that can be attached to a schema to render in json-ld and hence RDF using these mappings? Or reference implementations of a python module to perform these mappings etc?

**Comment by takuki** [comment] 2019-08-30 06:37
There is a pending WIP #744, which should address some of the points raised in this issue.

**Comment by sebastiankb** [comment] 2019-12-05 15:26
PR https://github.com/w3c/wot-thing-description/pull/744 is ready for review

**Comment by mmccool** [comment] 2019-12-09 14:24
@rob-metalinkage Merged #744 which addressed these issues.   The text of index.html will proceed into the publication process.  The update of the content and ontology files is in progress.

**Comment by mmccool** [comment] 2019-12-09 14:24
Will close for now, since we think the issue is addressed.  Will re-open if necessary.

**Closed by mmccool** 2019-12-09 14:24 UTC
Labels: by PR transition, ontology

**Comment by rob-metalinkage** [comment] 2019-12-11 01:42
I am happy with #744 - its a big PR so a bit difficult to follow but the TD section looks great to me:
https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/744.html#json-ld-ctx-usage

I dont see how my original concerns over how to use the artefact are addressed - i'll have to dig deeper - it would have been helpful to call out the specific commits that addressed my comment.

**Comment by vcharpenay** [comment] 2019-12-11 08:31
Sure. If you look now in the master branch, [`jsonschema.html`](https://github.com/w3c/wot-thing-description/blob/master/ontology/jsonschema.html) has now been extended with comments on how to map JSON Schema definitions to RDF.

The HTML file has not been updated [on github.io](https://w3c.github.io/wot-thing-description/ontology/jsonschema.html), though, and I do not understand why... I opened an issue on that: #868.
