### ISSUE TITLE
[TD Playground] JSON Schema bug: "events" should not be mandatory

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-thing-description#153] opened 2018-06-18 13:55 UTC
The JSON Schema validation at:
http://plugfest.thingweb.io/playground/
makes "events" mandatory.

This does not reflect the spec, where events are not mandatory.

**Comment by egekorkan** [comment] 2018-06-18 14:22
Can you post the TD that is not validated? I have posted the TD example from the spec (MyLampThing) and removed the events and there were no errors

**Comment by mlagally** [comment] 2018-06-18 14:52
{
	"@context": [
		"https://w3c.github.io/wot/w3c-wot-td-context.jsonld"
	],
	"name": "BMW_X5_TD",
	"description": "http://xxxxxxxx/v2/north/",
	"id": "urn:com:EURECOM-TDs:BMW_X5_TD",
	"base": "http://<tbd>",
	"createdAsString": "2018-06-18T13:20:01.319Z",
	"created": 1529328001319,
	"lastModifiedAsString": "2018-06-18T13:20:01.319Z",
	"lastModified": 1529328001319,
	"userLastModified": "auto-generated by dm2td converter",
	"support": "https://servient.example.com/contact",
	"properties": {
		"gearPosition": {
			"name": "gearPosition",
			"description": "sensor/gearPosition",
			"type": "string",
			"writable": false,
			"label": "gearPosition"
		},
		"left-front-door": {
			"name": "left-front-door",
			"description": "sensor/left-front-door",
			"type": "string",
			"writable": false,
			"label": "left-front-door"
		},
		"right-front-door": {
			"name": "right-front-door",
			"description": "sensor/right-front-door",
			"type": "string",
			"writable": false,
			"label": "right-front-door"
		},
		"leftRearDoor": {
			"name": "leftRearDoor",
			"description": "sensor/leftRearDoor",
			"type": "string",
			"writable": false,
			"label": "leftRearDoor"
		},
		"rightRearDoor": {
			"name": "rightRearDoor",
			"description": "sensor/rightRearDoor",
			"type": "string",
			"writable": false,
			"label": "rightRearDoor"
		},
		"left-front-window": {
			"name": "left-front-window",
			"description": "actuator/left-front-window/status",
			"type": "string",
			"writable": false,
			"label": "left-front-window"
		},
		"right-front-window": {
			"name": "right-front-window",
			"description": "actuator/right-front-window/status",
			"type": "string",
			"writable": false,
			"label": "right-front-window"
		},
		"leftRearWindow": {
			"name": "leftRearWindow",
			"description": "actuator/leftRearWindow/status",
			"type": "string",
			"writable": false,
			"label": "leftRearWindow"
		},
		"rightRearWindow": {
			"name": "rightRearWindow",
			"description": "actuator/rightRearWindow/status",
			"type": "string",
			"writable": false,
			"label": "rightRearWindow"
		}
	},
	"actions": {
		"left-headlight": {
			"name": "left-headlight",
			"description": "actuator/left-headlight/turnon",
			"label": "left-headlight"
		},
		"right-headlight": {
			"name": "right-headlight",
			"description": "actuator/left-headlight/turnon",
			"label": "right-headlight"
		}
	}
}

**Comment by sebastiankb** [comment] 2018-06-18 15:04
I did a quick check and I cannot discover any errors either:

![image](https://user-images.githubusercontent.com/13832739/41544678-996157d2-7319-11e8-8618-ae8d969da142.png)

**Comment by mlagally** [comment] 2018-06-18 15:07
Are we using the same version of the tool?
I used:
http://plugfest.thingweb.io/playground/

**Comment by mlagally** [comment] 2018-06-18 15:08
![screen shot 2018-06-18 at 17 08 00](https://user-images.githubusercontent.com/31951801/41544933-4752e018-731a-11e8-975d-26e9ca94f318.png)

**Comment by egekorkan** [comment] 2018-06-18 16:39
I think I have found the problem, I was doing some extra verification and looking for td.events without checking whether it actually exists. In Mozilla and Chrome this doesn't seem to be a problem because of the javascript engine but I think you are using Safari and there this problem is actually detected. I am updating soon.

**Comment by egekorkan** [comment] 2018-06-18 17:07
It should be fixed now. And could you post the upcoming issues in https://github.com/thingweb/thingweb-playground :)

**Comment by sebastiankb** [comment] 2018-06-19 07:54
Thanks! 

@mlagally Most likely I had a cached version in my browser... I tested again in it works fine. BTW: In the TD there is the term "name" used at the interaction level. It should be "label".

**Comment by mlagally** [comment] 2018-06-19 14:24
@egekorkan thanks, it validates my TD without errors now.

**Comment by sebastiankb** [comment] 2018-06-21 14:21
I think, the issue is solved and can be closed.

**Closed by sebastiankb** 2018-06-21 14:21 UTC
