### ISSUE TITLE
dateTime reference when mapping to JSON types [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/wot-thing-description#641] opened 2019-05-07 16:30 UTC
6.1.1 Mapping to JSON Types
https://cdn.staticaly.com/gh/w3c/wot-thing-description/TD-TAG-review/index.html?env=dev#td-basic-types-mapping

> Vocabulary terms that use simple type dateTime MUST be serialized as JSON string and have the lexical form YYYY-MM-DDThh:mm:ssZ. This lexical form represents a subset of the XSD built-in dateTime datatype , itself inspired by the ISO standard for dates and times [ISO8601].

While this is correct, a better reference to this specific format would be [RFC3339]'s `date-time`. This is exactly this format.

Also, the pattern given includes `Z`, which, when it appears as the literal string `Z` means "UTC". But it can also mean that offsets such as `-03:00` or `+08:00` are also permitted. Please clarify what is intended here and note that UTC is recommended, even if offsets are permitted.

**Comment by mkovatsc** [comment] 2019-05-07 17:06
Thank you, especially RFC 3339 appears useful!

**Comment by mkovatsc** [comment] 2019-05-07 18:02
Waiting on the discussion in #586 to decide how to address this.

**Comment by vcharpenay** [comment] 2019-05-09 10:48
The issue referenced above was closed, also solving the present issue.

**Comment by aphillips** [comment] 2019-05-09 13:53
The wording to fix #586 isn't quite right.

> Values that are of type dateTime MUST be serialized as JSON strings following the timestamp format specified by [RFC3339]. Timestamps included in a TD SHOULD have the lexical form YYYY-MM-DDThh:mm:ssZ, where YYYY, MM and DD respectively encode a year, a month and a day (i.e. a date) and where hh, mm and ss respectively encode hours, minutes and seconds (i.e. a time). Other elements of the lexical form (-, T, Z) are verbatim. It implies that implementations need to support time zones, Z being interpreted as the UTC+00 time zone.

My comments:

1. RFC3339 has a number of formats defined. You should reference the `date-time` format by name.
1. Your list of verbatim elements is missing the colon and dot.
1. `Z` represents the `UTC` time zone. If you're going to say `UTC+00:00` you need the additional minutes part. But I don't think it is necessary to include the (lack of) offset.
1. "It implies that implementations need to support time zones" isn't really correct. You need a time zone or at least a local time offset in order to render wall time (see [here](https://www.w3.org/TR/timezone/)). Most machines count time in UTC, so generating and processing time values this way is trivial.
1. The normative "Timestamps included in a TD SHOULD..." strikes me as redundant and, in fact, somewhat harmful. If you just required RFC3339 date-time (MUST) in the previous sentence, the SHOULD in this one is just confusing--the date time format is this format.
1. I think you should not disallow offsets. They don't really involve time zones. They just represent the amount of time you add/subtract from the timestamp to get UTC (epoch) time. If someone's device is constrained in a way that is generates offsets, well, the parsing for ISO8601 is wide spread and the handling is trivial. 

I'd suggest:

> Values that are of type dateTime MUST be serialized using the [[RFC3339]] `date-time` format. This format has the lexical form `YYYY-MM-DDThh:mm:ssZ`, representing a timestamp. `dateTime` values SHOULD use the literal `Z` representing the UTC time zone instead of an offset.

**Comment by mmccool** [comment] 2019-05-09 14:52
- i18n recommends that we do not disallow offsets.

**Comment by mkovatsc** [comment] 2019-05-09 15:04
That is what was intended. I think this text is just a bit misleading:
> Other elements of the lexical form (-, T, Z) are verbatim. It implies that implementations need to support time zones, Z being interpreted as the UTC+00 time zone.

**Comment by mmccool** [comment] 2019-05-09 16:14
Matthias, we are dealing with text direction right now.  If you want to do a PR for this issue, that would be great ;)

**Comment by aphillips** [comment] 2019-09-26 15:55
LGTM. I18N is satisfied with the changes in the current draft.

**Comment by sebastiankb** [comment] 2019-09-27 15:22
thank you for your feedback. I will close this issue.

**Closed by sebastiankb** 2019-09-27 15:22 UTC
Labels: Needs review, i18n-comment
