### ISSUE TITLE
Check against i18n Review Checklist

### ISSUE THREAD

**Issue by takuki** [w3c/wot-thing-description#582] opened 2019-04-26 00:48 UTC
Short i18n review checklist is [here](http://w3c.github.io/i18n-activity/reviews/shortchecklist)

1. [x] If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),

    The TD spec itself does not contain such text.
    However, the TD spec defines fields "support", "description" and "title" with which the authors of TD can add natural language texts that can be read by a human.
    For Language Basics, see issue #[TBD] (@mryuichi )
    For Language Values, see issue #595 (@ashimura )
    For Declaring language at the resource level, see issue #584 (@mmccool)
    For Handling base direction for strings, see issue #585 (@mmccool)
    
2. [x] If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics.

    **N/A (Not Applicable)**
    TD authors are not expected to produce typographically appealing text.
    TD does not provide a means to do so, either.

3. [x] If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc.

    **N/A (Not Applicable)**
    TD users are not expected to do such operations.
    TD does not provide a means to do so, either.

4. [x] If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers
    - TD spec contains "id" field of a Thing for identifying a Thing.
    - The "id" field is defined to be of anyURI type of XSD 1.1.
    - An implementation of TD itself does not do an operation of matching identifiers.
        - However, TDs may be entered into other systems such as RDF databases, that can then be searched using SPARQL, for example.
        - TD depends on these external standards (e.g. RDF and SPARQL) to do the right thing on identifier matching.
　
5. [x] If the spec (or its implementation) sorts text

    **N/A (Not Applicable)**
    TD spec or its implementation do not involve sorting text.

6. [x] If the spec (or its implementation) captures user input

    **N/A (Not Applicable)**
    TD spec or its implementation do not involve capturing user input.

7. [x] If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries

    TD format has data fields that contain time.
    See issue #578 - i18n checklist for Working with time (@ToruKawaguchi)

8. [x] If the spec (or its implementation) allows any character encoding other than UTF-8.

    **N/A (Not Applicable)**
    UTF-8 is the only valid encoding for TD format.

9. [x] If the spec (or its implementation) defines markup.

    **N/A (Not Applicable)**
    TD spec does not define markup.

10. [x] If the spec (or its implementation) deals with names, addresses, time & date formats, etc

    TD spec has data fields that contains names, time & date and numbers.
    For names, see issue #580 - i18n checklist for Working with personal names. (@chachamimm)
    For numbers, see issue #579 - i18n checklist for Working with numbers. (@takuki)
    For time & date, see issue #578 - i18n checklist for Working with time. (@ToruKawaguchi)

11. [x] If the spec (or its implementation) describes a format or data that is likely to need localization.

    TD describes data that is likely to need localization such as description and title, which may be used for user interfaces related to the Thing.   However, in each case such strings can also be given using MultiLanguage objects (given as "descriptions" and "titles") which allow the storage and labelling of localized alternatives.  The TD spec also supports single-language default values for each such string which can however be set via language negotiation from the corresponding MultiLanguage data.

    (Ensure that there’s an approach in place which allows effective storage and labelling of, and access to localised alternatives for strings, text, images, etc.
    See issue #583 (@mmccool))

12. [x] If the spec (or its implementation) makes any reference to or relies on any cultural norms

    **N/A (Not Applicable)**
    TD spec neither depends or refers to any cultural norms.

**Comment by mkovatsc** [comment] 2019-05-09 23:33
The remaining unchecked item was actually a duplicate of #584 
Closing.

**Closed by mkovatsc** 2019-05-09 23:33 UTC
Labels: i18n-self-check
